version = 1

test_patterns = ["**/*.go"]

exclude_patterns = ["**/*_test.go"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/jxsl13/TeeworldsEconDiscordModerationBot"]
